### ISSUE TITLE
Update needed

### ISSUE THREAD

**Issue by Knito58** [SE7-KN8/wool#3]
wool 1.1.5 on MC 1.14 Pre-Release 5 with Fabric 0.2.7+build.123

Right clicking the shearer crashes the game. 
[spoiler]
Time: 20.04.19 02:11
Description: Rendering screen

....

java.lang.NoSuchFieldError: field_2563
	at com.github.se7_kn8.wool.client.gui.BaseContainerScreen.method_2389(BaseContainerScreen.java:17)
	at net.minecraft.class_465.render(class_465.java:83)
	at net.minecraft.class_757.method_3192(class_757.java:686)
	at net.minecraft.class_310.method_1523(class_310.java:946)
	at net.minecraft.class_310.method_1514(class_310.java:410)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:130)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

**Comment by se7kn8** [comment]
Sorry for the delay: [Here's](https://minecraft.curseforge.com/projects/wool/files/2704067) a new release which should work with the latest 1.14 (it also introduces new features)

**Comment by Knito58** [comment]
Thank you! Works now :)
